AllCops:
  Exclude:
    - 'Gemfile'
    - 'Gemfile.lock'
    - '.gitignore'
    - 'readme.md'
    - 'Rakefile'
    - 'bin/console'
    - 'spec/spec_helper.rb'
    - 'spec/codebreaker_spec.rb'
    - 'lib/codebreaker/version.rb'
